stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/data.csv
    - src/preprocess.py
    params:
    - data
    - preprocessing
    outs:
    - data/preprocessed_data.csv
  train:
    cmd: python src/train.py
    deps:
    - data/preprocessed_data.csv
    - src/train.py
    params:
    - preprocessing
    - train
    outs:
    - models/LinearRegression_model.joblib
    - models/RandomForest_model.joblib
    - models/GradientBoosting_model.joblib
    - models/champion_model.joblib
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/preprocessed_data.csv
    - models/champion_model.joblib
    - src/evaluate.py
    params:
    - evaluate
    outs:
    - metrics.json
