stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/data.csv
    - src/preprocess.py
    params:
    - data
    - preprocessing
    outs:
    - data/preprocessed_data.csv
  train:
    cmd: python src/train.py
    deps:
    - data/preprocessed_data.csv
    - src/train.py
    params:
    - preprocessing
    - train
    outs:
    - models/model.joblib
