data:
  input_path: "data/data.csv"
  output_path: "data/preprocessed_data.csv"

train:
  test_size: 0.2
  random_state: 42
  model_path: "models"
  linear_regression:
    hyperparameters:
      fit_intercept: [True, False]
  random_forest:
    hyperparameters:
      n_estimators: [100, 200, 300]
      max_depth: [null, 5, 10, 15, 20]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]
  gradient_boosting:
    hyperparameters:
      n_estimators: [100, 200, 300]
      learning_rate: [0.01, 0.05, 0.1]
      max_depth: [3, 5, 7, 9]
      min_samples_split: [2, 5]

preprocessing:
  target: price
  features: [area, bedrooms, bathrooms, stories, parking]

evaluate:
  model_file: "models/champion_model.joblib"  
  metrics_file: "metrics.json"  
  feature_importance_file: "feature_importance.csv" 